name: Publish Package on NPM

on:
  push:
    branches: ['main']
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: JS-DevTools/npm-publish@v4}