name: Publish Package on NPM

on:
  push:
    branches: ['main']
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JS-DevTools/npm-publish@v3
        with:
          package: lib
          token: ${{ secrets.NPM_TOKEN }}